<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit303ab9e9dae33ccbbfcecf2d080c8369
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'OCooking\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OCooking\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'AltoRouter' => __DIR__ . '/..' . '/altorouter/altorouter/AltoRouter.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit303ab9e9dae33ccbbfcecf2d080c8369::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit303ab9e9dae33ccbbfcecf2d080c8369::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit303ab9e9dae33ccbbfcecf2d080c8369::$classMap;

        }, null, ClassLoader::class);
    }
}
